name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate with GitHub API
      id: authenticate
      env:
        GH_APP_CLIENT_ID: ${{ secrets.GH_APP_CLIENT_ID }}
        GH_APP_CLIENT_SECRET: ${{ secrets.GH_APP_CLIENT_SECRET }}
      run: |
        CLIENT_ID=${{ env.GH_APP_CLIENT_ID }}
        CLIENT_SECRET=${{ env.GH_APP_CLIENT_SECRET }}
        TOKEN=$(curl -u $CLIENT_ID:$CLIENT_SECRET -d '{"scopes":["repo", "user"], "note":"GitHub Action"}' https://api.github.com/authorizations | jq -r '.token')
        echo "GITHUB_TOKEN=$TOKEN" >> $GITHUB_ENV

    - name: Call GitHub API to list repositories
      run: |
        curl -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" https://api.github.com/user/repos
